config/routes.rb
Rails.application.routes.draw do
  root 'setors#index'

  devise_for :usuarios, :path => 'usuarios/security'
  resources :usuarios
  resources :empresas do
    get 'usuarios/' => 'usuarios#index_usuario_empresa'
    post 'usuarios/' => 'usuarios#create_usuario_empresa', as: 'usuario_create'
    get 'usuarios/:id/edit' => 'usuarios#edit_usuario_empresa', as: 'usuario_edit'
    get 'usuarios/new' => 'usuarios#new_usuario_empresa', as: 'usuario_new'
    get 'usuarios/:id' => 'usuarios#show_usuario_empresa', as: 'usuario'
    put 'usuarios/:id' => 'usuarios#update_usuario_empresa', as: 'usuario_update'
    patch 'usuarios/:id' => 'usuarios#update_usuario_empresa', as: 'usuario_patch_update'
    delete 'usuarios/:id' => 'usuarios#destroy_usuario_empresa', as: 'usuario_delete'

  end

  resources :setors do
    resources :organizacaos do
      resources :oferta
    end
  end

end

app/models/setor.rb
class Setor < ActiveRecord::Base
  has_many :organizacaos, dependent: :destroy
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates_presence_of :nome
end

app/controllers/setors_controller.rb
class SetorsController < ApplicationController
  before_action :set_setor, only: [:show, :edit, :update, :destroy]

  # GET /setors
  # GET /setors.json
  def index
    @setors = Setor.all
  end

  # GET /setors/1
  # GET /setors/1.json
  def show
  end

  # GET /setors/new
  def new
    @setor = Setor.new
  end

  # GET /setors/1/edit
  def edit
  end

  # POST /setors
  # POST /setors.json
  def create
    @setor = Setor.new(setor_params)

    respond_to do |format|
      if @setor.save
        format.html { redirect_to @setor, notice: 'Setor was successfully created.' }
        format.json { render :show, status: :created, location: @setor }
      else
        format.html { render :new }
        format.json { render json: @setor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setors/1
  # PATCH/PUT /setors/1.json
  def update
    respond_to do |format|
      if @setor.update(setor_params)
        format.html { redirect_to @setor, notice: 'Setor was successfully updated.' }
        format.json { render :show, status: :ok, location: @setor }
      else
        format.html { render :edit }
        format.json { render json: @setor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setors/1
  # DELETE /setors/1.json
  def destroy
    @setor.destroy
    respond_to do |format|
      format.html { redirect_to setors_url, notice: 'Setor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setor
      @setor = Setor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setor_params
      params.require(:setor).permit(:nome, :descricao, :avatar)
    end
end

app/helpers/setors_helper.rb
module SetorsHelper
end

app/views/setors/_form.html.erb
<%= form_for( @setor, :html => { :multipart => true } ) do |f| %>
  <% if @setor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setor.errors.count, "error") %> prohibited this setor from being saved:</h2>

      <ul>
      <% @setor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/setors/edit.html.erb
<h1>Editing Setor</h1>

<%= render 'form' %>

<%= link_to 'Show', @setor %> |
<%= link_to 'Back', setors_path %>

app/views/setors/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<%= link_to 'Novo Setor', new_setor_path %>
<br>

<h1>Setores</h1>

<table>
  <tbody>
    <% @setors.each do |setor| %>
      <tr>
        <td>
          <%= link_to image_tag(setor.avatar.url(:medium), :border =>0), setor_organizacaos_path(setor) %>
          <br><%= setor.nome %>
          <br><%= setor.descricao %>
        </td>
        <td>
          <ul>
            <li><%= link_to 'Show', setor %></li>
            <li><%= link_to 'Edit', edit_setor_path(setor) %></li>
            <li><%= link_to 'Destroy', setor, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/setors/new.html.erb
<h1>Novo Setor</h1>

<%= render 'form' %>

<%= link_to 'Back', setors_path %>

app/views/setors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @setor.avatar.url(:thumb) %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @setor.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @setor.descricao %>
</p>

<%= link_to 'Edit', edit_setor_path(@setor) %> |
<%= link_to 'Back', setors_path %>