config/routes.rb
Rails.application.routes.draw do
  root 'setors#index'

  devise_for :usuarios, :path => 'usuarios/security'
  resources :usuarios
  resources :empresas do
    get 'usuarios/' => 'usuarios#index_usuario_empresa'
    post 'usuarios/' => 'usuarios#create_usuario_empresa', as: 'usuario_create'
    get 'usuarios/:id/edit' => 'usuarios#edit_usuario_empresa', as: 'usuario_edit'
    get 'usuarios/new' => 'usuarios#new_usuario_empresa', as: 'usuario_new'
    get 'usuarios/:id' => 'usuarios#show_usuario_empresa', as: 'usuario'
    put 'usuarios/:id' => 'usuarios#update_usuario_empresa', as: 'usuario_update'
    patch 'usuarios/:id' => 'usuarios#update_usuario_empresa', as: 'usuario_patch_update'
    delete 'usuarios/:id' => 'usuarios#destroy_usuario_empresa', as: 'usuario_delete'

  end

  resources :setors do
    resources :organizacaos do
      resources :oferta
    end
  end

end

app/views/shared/_header.html.erb
<div id="user_nav">
  <% if usuario_signed_in? %>
    Email, <%= link_to current_usuario.email, edit_usuario_registration_path %>?
    <%= link_to "Sair", destroy_usuario_session_path,  method: :delete %>

    <% if current_usuario.admin %>
      <br><%= link_to "Usuários", usuarios_path %> |
      <%= link_to "Empresas", empresas_path %>
    <% elsif !current_usuario.empresa %>
      <br><h4><%= link_to "Entre em contato com o suporte para criar sua empresa." %></h4>
    <% elsif current_usuario.empresa_admin %>
      <br><%= link_to "Usuários", empresa_usuarios_path(current_usuario.empresa) %>
    <% end %>
  <% else %>
      <%= link_to "Acesse", new_usuario_session_path %> |
      <%= link_to "Registre-se", new_usuario_registration_path %>
  <% end %>
</div>