config/routes.rb
Rails.application.routes.draw do
  root 'setors#index'

  devise_for :usuarios, :path => 'usuarios/security'
  resources :usuarios
  resources :empresas do
    get 'usuarios/' => 'usuarios#index_usuario_empresa'
    post 'usuarios/' => 'usuarios#create_usuario_empresa', as: 'usuario_create'
    get 'usuarios/:id/edit' => 'usuarios#edit_usuario_empresa', as: 'usuario_edit'
    get 'usuarios/new' => 'usuarios#new_usuario_empresa', as: 'usuario_new'
    get 'usuarios/:id' => 'usuarios#show_usuario_empresa', as: 'usuario'
    put 'usuarios/:id' => 'usuarios#update_usuario_empresa', as: 'usuario_update'
    patch 'usuarios/:id' => 'usuarios#update_usuario_empresa', as: 'usuario_patch_update'
    delete 'usuarios/:id' => 'usuarios#destroy_usuario_empresa', as: 'usuario_delete'

  end

  resources :setors do
    resources :organizacaos do
      resources :oferta
    end
  end

end

app/models/organizacao.rb
class Organizacao < ActiveRecord::Base
  belongs_to :setor
  has_many :oferta, dependent: :destroy
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates_presence_of :nome, :setor_id
end

app/controllers/organizacaos_controller.rb
class OrganizacaosController < ApplicationController
  before_action :set_organizacao, only: [:show, :edit, :update, :destroy]
  before_action :set_setor, only: [:index, :new, :create, :edit, :update, :destroy]

  # GET /:setor_id/organizacaos
  # GET /:setor_id/organizacaos.json
  def index
    @organizacaos = @setor.organizacaos.all
  end

  # GET /:setor_id/organizacaos/1
  # GET /organizacaos/1.json
  def show
  end

  # GET /:setor_id/organizacaos/new
  # GET /:setor_id/organizacaos/new
  def new
    @organizacao = Organizacao.new
    @organizacao.setor_id = @setor.id
  end

  # GET /organizacaos/1/edit
  def edit
  end

  # POST /organizacaos
  # POST /organizacaos.json
  def create
    @organizacao = Organizacao.new(organizacao_params)
    @organizacao.setor_id = @setor.id

    respond_to do |format|
      if @organizacao.save
        format.html { redirect_to [@setor, @organizacao], notice: 'Organização criada com sucesso!' }
        format.json { render :show, status: :created, location: @organizacao }
      else
        format.html { render :new }
        format.json { render json: @organizacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizacaos/1
  # PATCH/PUT /organizacaos/1.json
  def update
    respond_to do |format|
      if @organizacao.update(organizacao_params)
        format.html { redirect_to [@setor, @organizacao], notice: 'Organização foi atualizada!' }
        format.json { render :show, status: :ok, location: @organizacao }
      else
        format.html { render :edit }
        format.json { render json: @organizacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizacaos/1
  # DELETE /organizacaos/1.json
  def destroy
    @organizacao.destroy
    respond_to do |format|
      format.html { redirect_to [@setor, @organizacao], notice: 'Organização foi excluida com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organizacao
      @organizacao = Organizacao.find(params[:id])
    end

    def set_setor
      @setor = Setor.find(params[:setor_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organizacao_params
      params.require(:organizacao).permit(:nome, :descricao, :setor_id, :avatar)
    end
end

app/helpers/organizacaos_helper.rb
module OrganizacaosHelper
end

app/views/organizacaos/_form.html.erb
<%= form_for( [@setor, @organizacao], :html => { :multipart => true } ) do |f| %>
  <% if @organizacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organizacao.errors.count, "error") %> prohibited this organizacao from being saved:</h2>

      <ul>
      <% @organizacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizacaos/edit.html.erb
<h1>Editar Organização</h1>

<%= render 'form' %>

<%= link_to 'Show', setor_organizacao_path(@organizacao.setor_id, @organizacao) %> |
<%= link_to 'Back', setor_organizacaos_path(@organizacao.setor_id) %>

app/views/organizacaos/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to "Cadastrar nova orgarnização", new_setor_organizacao_path %>
<br>
<br>

<%= @setor.nome + " > Organizações" %>

<table>
  <tbody>
    <% @organizacaos.each do |organizacao| %>
      <tr>
        <td>
          <%= link_to image_tag(organizacao.avatar.url(:medium), :border =>0), setor_organizacao_oferta_path(@setor, organizacao) %>
          <br><%= organizacao.nome %>
          <br><%= organizacao.descricao %>
        </td>
        <td>
          <ul>
            <li><%= link_to 'Show', setor_organizacao_path(organizacao.setor_id, organizacao) %></li>
            <li><%= link_to 'Edit', edit_setor_organizacao_path(organizacao.setor_id, organizacao) %></li>
            <li><%= link_to 'Delete', [@setor, organizacao], method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/organizacaos/new.html.erb
<h1>Criar Organização</h1>

<%= render 'form' %>

<%= link_to 'Back', setor_organizacaos_path(@setor) %>

app/views/organizacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @organizacao.avatar.url(:thumb) %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @organizacao.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @organizacao.descricao %>
</p>

<%= link_to 'Edit', edit_setor_organizacao_path(@organizacao.setor_id, @organizacao) %> |
<%= link_to 'Back', setor_organizacaos_path(@organizacao.setor_id) %>