config/routes.rb
Rails.application.routes.draw do
  root 'setors#index'

  devise_for :usuarios, :path => 'usuarios/security'
  resources :usuarios
  resources :empresas do
    get 'usuarios/' => 'usuarios#index_usuario_empresa'
    post 'usuarios/' => 'usuarios#create_usuario_empresa', as: 'usuario_create'
    get 'usuarios/:id/edit' => 'usuarios#edit_usuario_empresa', as: 'usuario_edit'
    get 'usuarios/new' => 'usuarios#new_usuario_empresa', as: 'usuario_new'
    get 'usuarios/:id' => 'usuarios#show_usuario_empresa', as: 'usuario'
    put 'usuarios/:id' => 'usuarios#update_usuario_empresa', as: 'usuario_update'
    patch 'usuarios/:id' => 'usuarios#update_usuario_empresa', as: 'usuario_patch_update'
    delete 'usuarios/:id' => 'usuarios#destroy_usuario_empresa', as: 'usuario_delete'

  end

  resources :setors do
    resources :organizacaos do
      resources :oferta
    end
  end

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  has_many :usuarios
  has_many :carrinhos, dependent: :destroy
  accepts_nested_attributes_for :usuarios
  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :empresa
  has_many :carrinhos, dependent: :destroy
  accepts_nested_attributes_for :empresa
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/usuario-avatar-default.png"
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates_uniqueness_of :email

  # TODO Estou passando por alguns problemas ao tentar realizar update no usuario sem password.
  # validates_presence_of :password, on: :create
  # validates_length_of :password, minimum: 6
  # has_secure_password is require a column password_digest in migrate.

  # Devise GEM - Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :authenticate_usuario!
  before_action :check_has_empresa_and_usuario_permission
  before_action :set_empresa, only: [:index, :show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = @empresa ? [@empresa] : Empresa.all
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
    @empresa ? @empresa : head(403)
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
    @empresa.usuarios.build
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      if ( current_usuario.admin && params[:id] )
        @empresa = Empresa.find(params[:id])
      elsif ( current_usuario.empresa_admin && current_usuario.empresa )
        @empresa = Empresa.find(current_usuario.empresa)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:nome_fantasia, :razao_social, :cnpj, :descricao, :logo, :usuarios_attributes => [])
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :check_is_admin, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  before_action :check_has_empresa_and_usuario_permission, only: [:index_usuario_empresa, :show_usuario_empresa, :new_usuario_empresa, :edit_usuario_empresa, :create_usuario_empresa, :update_usuario_empresa, :destroy_usuario_empresa]
  before_action :set_usuario, only: [:show, :show_usuario_empresa, :edit, :edit_usuario_empresa, :update, :update_usuario_empresa, :destroy, :destroy_usuario_empresa]
  before_action :set_empresa, only: [:index_usuario_empresa, :show_usuario_empresa, :new_usuario_empresa, :edit_usuario_empresa, :create_usuario_empresa, :update_usuario_empresa, :destroy_usuario_empresa]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all.where.not(id: current_usuario)
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)
    @usuario.empresa = @empresa

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      @usuario.empresa = @empresa
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to @usuario, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /empresas/:empresa_id/usuarios
  # GET /empresas/:empresa_id/usuarios.json
  def index_usuario_empresa
    @usuarios = @empresa.usuarios.all.where.not(id: current_usuario)
    render 'empresas/usuarios/index'
  end

  # GET /empresas/:empresa_id/usuarios/1
  # GET /empresas/:empresa_id/usuarios/1.json
  def show_usuario_empresa
    render 'empresas/usuarios/show'
  end

  # GET /empresas/:empresa_id/usuarios/new
  def new_usuario_empresa
    @usuario = Usuario.new
    render 'empresas/usuarios/new'
  end

  # GET /empresas/:empresa_id/usuarios/1/edit
  def edit_usuario_empresa
    render 'empresas/usuarios/edit'
  end

  # POST /empresas/:empresa_id/usuarios
  # POST /empresas/:empresa_id/usuarios.json
  def create_usuario_empresa
    @usuario = Usuario.new(usuario_params)
    @usuario.empresa = @empresa

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to empresa_usuario_path(@empresa, @usuario), notice: 'Usuario was successfully created.' }
        format.json { render 'empresas/usuarios/show', status: :created, location: @usuario }
      else
        format.html { render 'empresas/usuarios/new' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/:empresa_id/usuarios/1
  # PATCH/PUT /empresas/:empresa_id/usuarios/1.json
  def update_usuario_empresa
    respond_to do |format|
      @usuario.empresa = @empresa
      if @usuario.update(usuario_params)
        format.html { redirect_to empresa_usuario_path(@empresa, @usuario), notice: 'Usuario was successfully updated.' }
        format.json { render 'empresas/usuarios/show', status: :ok, location: @usuario }
      else
        format.html { render 'empresas/usuarios/edit' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/:empresa_id/usuarios/1
  # DELETE /empresas/:empresa_id/usuarios/1.json
  def destroy_usuario_empresa
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to [@empresa, @usuario], notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    def set_empresa
      if ( current_usuario.empresa )
        @empresa = Empresa.find(current_usuario.empresa)
      else
        @empresa = Empresa.find(params[:empresa_id])
      end
    end

  # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :telefone, :email, :password, :password_confirmation, :facebook_url, :twitter_url, :avatar, :admin, :empresa_admin, :empresa_id, :empresa_attributes => [])
    end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/empresas/usuarios/_form.html.erb
<%= form_for( [@empresa, @usuario], :html => { :multipart => true } ) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, autofocus: true %>
    <% if current_usuario.admin || current_usuario.empresa_admin %>
      <%= f.check_box :empresa_admin, class: :checkbox %>
      <%= f.label "Admin da empresa?", class: :checkbox %>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
      <em>Mínimo em caracteres: <%= @minimum_password_length %></em>
    <% end %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/empresas/usuarios/edit.html.erb
<h1>Editar Usuário</h1>

<%= render 'empresas/usuarios/form' %>

<%= link_to 'Remove Account', empresa_usuario_delete_path(@empresa, @usuario), method: :delete, data: { confirm: 'Tem certeza?' } %> |
<%= link_to 'Show', empresa_usuario_path(@empresa, @usuario) %> |
<%= link_to 'Back', empresa_usuarios_path(current_usuario.admin ? @empresa : current_usuario.empresa) %>

app/views/empresas/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de usuários da empresa: <%= @empresa.nome_fantasia %></h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.telefone %></td>
        <td><%= image_tag usuario.avatar.url(:thumb) %></td>
        <td><%= link_to 'Show', empresa_usuario_path(@empresa, usuario) %></td>
        <td><%= link_to 'Edit', empresa_usuario_edit_path(@empresa, usuario) %></td>
        <td><%= link_to 'Destroy', empresa_usuario_delete_path(@empresa, usuario), method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><%= link_to 'Novo Usuario', empresa_usuario_new_path(current_usuario.admin ? @empresa : current_usuario.empresa) %>

app/views/empresas/usuarios/new.html.erb
<h1>Novo Usuário</h1>

<%= render 'empresas/usuarios/form' %>

<%= link_to 'Back', empresa_usuarios_path(current_usuario.admin ? @empresa : current_usuario.empresa) %>

app/views/empresas/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @usuario.avatar.url(:thumb) %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @usuario.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<%= link_to 'Edit', empresa_usuario_edit_path(@empresa, @usuario) %> |
<%= link_to 'Back', empresa_usuarios_path(current_usuario.empresa) %>